const plan=[
{name:"Upper A",ex:[["Bench Press",4,"6–8"],["Pull-Up / Lat Pulldown",4,"6–10"],["Incline DB Press",3,"8–10"],["Chest-Supported Row",3,"8–10"],["Lateral Raise",3,"12–15"],["Biceps Curl",3,"10–12"],["Triceps Pressdown",3,"10–12"]]},
{name:"Lower A",ex:[["Back Squat",4,"5–8"],["Romanian Deadlift",3,"6–10"],["Bulgarian Split Squat",3,"8–10 / leg"],["Leg Curl",3,"10–12"],["Calf Raise",3,"10–15"],["Core",3,"10–15"]]},
{name:"Upper B",ex:[["Overhead Press",4,"6–8"],["Barbell / Cable Row",4,"6–10"],["DB Bench Press",3,"8–10"],["Lat Pulldown",3,"8–12"],["Rear Delt Fly",3,"12–15"],["Hammer Curl",3,"10–12"],["Triceps Extension",3,"10–12"]]},
{name:"Lower B",ex:[["Deadlift / Trap Bar Deadlift",3,"4–6"],["Front Squat / Leg Press",3,"6–10"],["Walking Lunge",3,"10 / leg"],["Hip Thrust",3,"8–12"],["Leg Curl",3,"10–12"],["Core",3,"10–15"]]},
{name:"Optional Athletic",ex:[["Box Jump",4,"3"],["DB Push Press",3,"6"],["Farmer Carry",4,"30–40 m"],["Sled Push / Bike Sprint",6,"20–30 sec"],["Mobility",1,"10 min"]]}
];
let week=1,day=0; const $=s=>document.querySelector(s); const key=(w,d,e,s,f)=>`w${w}-d${d}-e${e}-s${s}-${f}`;
function inherited(w,d,e,s){for(let x=w;x>=1;x--){let v=localStorage.getItem(key(x,d,e,s,"kg"));if(v)return v}return""}
function inheritedCheck(w,f){for(let x=w;x>=1;x--){let v=localStorage.getItem(`check-w${x}-${f}`);if(v)return v}return""}
function exerciseNoteKey(w,d,e){return`w${w}-d${d}-e${e}-note`}
function inheritedExerciseNote(w,d,e){for(let x=w;x>=1;x--){let v=localStorage.getItem(exerciseNoteKey(x,d,e));if(v)return v}return""}
function renderDays(){ $("#days").innerHTML=plan.map((x,i)=>`<button class="${i===day?"active":""}" data-d="${i}">${i+1}. ${x.name}</button>`).join("");document.querySelectorAll("[data-d]").forEach(b=>b.onclick=()=>{day=+b.dataset.d;render()})}
function render(){week=+$("#week").value;$("#weekLabel").textContent=week;renderDays();let p=plan[day];$("#workout").innerHTML=`<div class="card"><h2>${p.name}</h2><p class="meta">Enter load and completed reps for each set.</p></div>`+p.ex.map((x,e)=>`<div class="card exercise"><h3>${x[0]}</h3><div class="meta">${x[1]} sets × ${x[2]} reps</div><div class="sets"><b>Set</b><b>kg</b><b>reps</b>${Array.from({length:x[1]},(_,s)=>{let kg=localStorage.getItem(key(week,day,e,s,"kg"))??inherited(week-1,day,e,s);let reps=localStorage.getItem(key(week,day,e,s,"reps"))??"";return`<span>${s+1}</span><input data-k="${key(week,day,e,s,"kg")}" value="${kg}" inputmode="decimal" placeholder="kg"><input data-k="${key(week,day,e,s,"reps")}" value="${reps}" inputmode="numeric" placeholder="reps">`}).join("")}</div><label class="exercise-note">Comment<textarea rows="2" data-note="${exerciseNoteKey(week,day,e)}" placeholder="How did this exercise feel?">${localStorage.getItem(exerciseNoteKey(week,day,e))??inheritedExerciseNote(week-1,day,e)}</textarea></label></div>`).join("");document.querySelectorAll("[data-note]").forEach(i=>i.onchange=()=>localStorage.setItem(i.dataset.note,i.value));document.querySelectorAll("[data-k]").forEach(i=>i.onchange=()=>localStorage.setItem(i.dataset.k,i.value));loadCheck()}
function ck(f){return`check-w${week}-${f}`}function loadCheck(){["bodyWeight","steps"].forEach(id=>{$("#"+id).value=localStorage.getItem(ck(id))||""});$("#notes").value=localStorage.getItem(ck("notes"))??inheritedCheck(week-1,"notes")}
$("#week").oninput=render;["bodyWeight","steps","notes"].forEach(id=>$("#"+id).onchange=e=>localStorage.setItem(ck(id),e.target.value));$("#reset").onclick=()=>{if(confirm("Clear entries for this week?")){Object.keys(localStorage).filter(k=>k.startsWith("w"+week+"-")||k.startsWith("check-w"+week+"-")).forEach(k=>localStorage.removeItem(k));render()}};render();